from vk_api.keyboard import VkKeyboard, VkKeyboardColor


region_keyboard = VkKeyboard(one_time=False)
region_keyboard.add_button('Псков', color=VkKeyboardColor.PRIMARY)
region_keyboard.add_button('Бежаницы', color=VkKeyboardColor.PRIMARY)
region_keyboard.add_button('Гдов', color=VkKeyboardColor.PRIMARY)
region_keyboard.add_line()
region_keyboard.add_button('Дедовичи', color=VkKeyboardColor.PRIMARY)
region_keyboard.add_button('Дно', color=VkKeyboardColor.PRIMARY)
region_keyboard.add_button('Красногородск', color=VkKeyboardColor.PRIMARY)
region_keyboard.add_line()
region_keyboard.add_button('Кунья', color=VkKeyboardColor.PRIMARY)
region_keyboard.add_button('Локня', color=VkKeyboardColor.PRIMARY)
region_keyboard.add_button('Невель', color=VkKeyboardColor.PRIMARY)
region_keyboard.add_line()
region_keyboard.add_button('Новоржев', color=VkKeyboardColor.PRIMARY)
region_keyboard.add_button('Новосокольники', color=VkKeyboardColor.PRIMARY)
region_keyboard.add_button('Опочка', color=VkKeyboardColor.PRIMARY)
region_keyboard.add_line()
region_keyboard.add_button('Остров', color=VkKeyboardColor.PRIMARY)
region_keyboard.add_button('Палкино', color=VkKeyboardColor.PRIMARY)
region_keyboard.add_button('Печоры', color=VkKeyboardColor.PRIMARY)
region_keyboard.add_line()
region_keyboard.add_button('Плюсса', color=VkKeyboardColor.PRIMARY)
region_keyboard.add_button('Порхов', color=VkKeyboardColor.PRIMARY)
region_keyboard.add_button('Пустошка', color=VkKeyboardColor.PRIMARY)
region_keyboard.add_line()
region_keyboard.add_button('Пушкинские горы', color=VkKeyboardColor.PRIMARY)
region_keyboard.add_button('Пыталово', color=VkKeyboardColor.PRIMARY)
region_keyboard.add_button('Себеж', color=VkKeyboardColor.PRIMARY)
region_keyboard.add_line()
region_keyboard.add_button('Струги Красные', color=VkKeyboardColor.PRIMARY)
region_keyboard.add_button('Великие Луки', color=VkKeyboardColor.PRIMARY)
region_keyboard.add_button('Усвяты', color=VkKeyboardColor.PRIMARY)

new_keyboard = VkKeyboard(one_time=True)
new_keyboard.add_button("Выбрать другой район", color=VkKeyboardColor.POSITIVE)

first_keyboard = VkKeyboard(one_time=True)
first_keyboard.add_button("Выбрать район", color=VkKeyboardColor.POSITIVE)

local_keyboard = VkKeyboard(one_time=True)
local_keyboard.add_button("Выбрать другой район", color=VkKeyboardColor.POSITIVE)
